default: &default
  adapter: postgresql
  host: <%= ENV.fetch('DB_HOST', 'localhost') %>
  pool: 5
  timeout: 5000
  user: <%= ENV.fetch('DB_USER', 'strava') %>
  password: <%= ENV.fetch('DB_PASSWORD', 'strava') %>

development:
  <<: *default
  database: strava_dev

test:
  <<: *default
  database: strava_test

production:
  <<: *default
  database: <%= ENV.fetch('DB_NAME', 'strava') %>
